# Environment Configuration
env:
  load_dotenv: true
  env_file: ".env"

extract:
  subgraph_id: ${SUBGRAPH_ID}
  api_key: ${API_KEY}
  batch_size: 1000
  max_retries: 3

# Transformation Configuration
transform:
  validation_rules:
    min_amount: 0
    max_amount: 1e12
  decimal_places: 18
  timestamp_format: "%Y-%m-%d %H:%M:%S"

# Loading Configuration
load:
  connection_string: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/moo" # Updated to match docker-compose credentials
  batch_size: 5000
  timeout: 300
  table_name: "swaps"
  if_exists: "append"
